name: Build/release

on:
  release:
    types: [prereleased]

jobs:
  release_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v3

      - name: Install Dependencies
        run: npm install

      - name: Publish
        run: npm run build:linux:release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release_mac:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Publish Arm
        run: npm run build:mac:arm:release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Intel
        run: npm run build:mac:intel:release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release_windows:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Publish
        run: npm run build:win:release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

